name: nexus
description: "Nexus is your all-in-one personal assistant app designed to simplify and streamline your daily life. Whether you need reminders, a secure place to store passwords, a hub for saving links, notes, and documents, or just an organized way to manage tasks, Nexus has you covered."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  system_theme: ^3.1.2
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  win32: ^5.10.0
  ffi: ^2.1.3
  hugeicons: ^0.0.7
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  iconsax: ^0.0.8
  fluentui_system_icons: ^1.1.270
  permission_handler: ^11.3.1
  another_dashed_container: ^1.0.0
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
