name: nexus
description: "Nexus is your all-in-one personal assistant app designed to simplify and streamline your daily life. Whether you need reminders, a secure place to store passwords, a hub for saving links, notes, and documents, or just an organized way to manage tasks, Nexus has you covered."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  system_theme: ^3.1.2
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  win32: ^5.10.0
  ffi: ^2.1.3
  hugeicons: ^0.0.7
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  iconsax: ^0.0.8
  permission_handler: ^11.3.1
  another_dashed_container: ^1.0.0
  shared_preferences: ^2.5.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  meta: ^1.15.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  awesome_snackbar_content: ^0.1.5
  home_widget: ^0.7.0+1
  shadcn_flutter: ^0.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: NovaFlat
      fonts:
        - asset: assets/fonts/NovaFlat-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf
    - family: GeistSans
      fonts:
        - asset: packages/shadcn_flutter/fonts/Geist-Black.otf
          weight: 800
        - asset: packages/shadcn_flutter/fonts/Geist-Bold.otf
          weight: 700
        - asset: packages/shadcn_flutter/fonts/Geist-Light.otf
          weight: 300
        - asset: packages/shadcn_flutter/fonts/Geist-Medium.otf
          weight: 500
        - asset: packages/shadcn_flutter/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: packages/shadcn_flutter/fonts/Geist-Thin.otf
          weight: 100
        - asset: packages/shadcn_flutter/fonts/Geist-UltraBlack.otf
          weight: 900
        - asset: packages/shadcn_flutter/fonts/Geist-UltraLight.otf
          weight: 200
        - asset: packages/shadcn_flutter/fonts/Geist-Regular.otf
          weight: 400

  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
